name: gradle-build-artifact-publish-workflow
on:
  workflow_dispatch:
jobs:

  clean_build_publish_job:
    name: clean_build_publish_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project from github repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Gradle clean build and scan
        run: ./gradlew clean build --scan

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish-build-reports-as-artifact
          path: build/reports/
          if-no-files-found: error
          retention-days: 5
